name: gist_manager
description: "Gist Manager is a Flutter application that allows you to manage your GitHub gists. It provides a convenient interface for viewing, searching, and sorting your gists. The app also includes a light and dark theme based on the Dracula color palette."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  markdown: ^7.2.2
  flutter_markdown: ^0.6.20
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
